## Импортировать NumPy под именем np

In [99]:
import numpy as np

## Напечатать версию и конфигурацию

In [100]:
x=np.__version__
print(x)
np.show_config()

1.20.0
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]


## Создать вектор (одномерный массив) размера 10, заполненный нулями

In [101]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


##  Создать вектор размера 10, заполненный единицами

In [102]:
print(np.ones(10))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


## Создать вектор размера 10, заполненный числом 2.5

In [103]:
print(np.full(10, 2.5))

[2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5 2.5]


## Как получить документацию о функции numpy.add из командной строки

In [104]:
python3 -c "import numpy; numpy.info(numpy.add)"

SyntaxError: invalid syntax (3809857200.py, line 1)

## Создать вектор размера 10, заполненный нулями, но пятый элемент равен 1

In [105]:
x=np.zeros(10)
x[4]=1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


## Создать вектор со значениями от 10 до 49

In [106]:
print(np.arange(10,50))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


## Развернуть вектор (первый становится последним)

In [107]:
x=np.arange(10)
print(x[::-1])

[9 8 7 6 5 4 3 2 1 0]


## Создать матрицу (двумерный массив) 3x3 со значениями от 0 до 8

In [108]:
print(np.arange(9).reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## Найти индексы ненулевых элементов в [1,2,0,0,4,0]

In [109]:
print(np.nonzero([1,2,0,0,4,0]))

(array([0, 1, 4], dtype=int64),)


## Создать 3x3 единичную матрицу

In [110]:
print(np.ones(9).reshape(3,3))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


##  Создать массив 3x3x3 со случайными значениями

In [111]:
print(np.random.random((3,3,3)))

[[[0.21914596 0.42936809 0.52932005]
  [0.48449278 0.49568834 0.42074793]
  [0.92304291 0.91191134 0.66642705]]

 [[0.51536778 0.71460381 0.85525334]
  [0.11377029 0.13877147 0.91668481]
  [0.00284463 0.77343215 0.65130443]]

 [[0.37008359 0.31246762 0.91112591]
  [0.57542104 0.01953947 0.35085632]
  [0.36374174 0.84466042 0.57846836]]]


## Создать массив 10x10 со случайными значениями, найти минимум и максимум

In [112]:
x=np.random.random((10,10))
print(x.min(), x.max())

0.01147816929632095 0.9930568150829573


## Создать случайный вектор размера 30 и найти среднее значение всех элементов

In [113]:
x=np.random.random(30)
print(x.mean())

0.49785014957783846


## Создать матрицу с 0 внутри, и 1 на границах

In [114]:
x=np.ones((5,5))
x[1:-1,1:-1]=0
print(x)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##  Создать 5x5 матрицу с 1,2,3,4 под диагональю

In [115]:
x=np.diag(np.arange(1, 5),k=-1)
print(x)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


##  Создать 8x8 матрицу и заполнить её в шахматном порядке


In [116]:
x=np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Дан массив размерности (6,7,8). Каков индекс (x,y,z) сотого элемента?

In [117]:
print(np.unravel_index(100, (6,7,8)))

(1, 5, 4)


##  Создать 8x8 матрицу и заполнить её в шахматном порядке, используя функцию tile

In [118]:
print(np.tile(np.array([[0,1],[1,0]]),(4,4)))

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


##  Перемножить матрицы 5x3 и 3x2

In [119]:
print(np.dot(np.ones((5,3)),np.ones((3,2))))

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


## Дан массив, поменять знак у элементов, значения которых между 3 и 8

In [120]:
x=np.arange(11)
x[(3 < x) & (x <= 8)] *= -1
print(x)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


##  Создать 5x5 матрицу со значениями в строках от 0 до 4

In [121]:
x=np.zeros((5,5))
x+=np.arange(5)
print(x)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


## Есть генератор, сделать с его помощью массив

In [122]:
def generate():
    for x in range(5):
        yield x
y= np.fromiter(generate(),dtype=float,count=-1)
print(y)

[0. 1. 2. 3. 4.]


##  Создать вектор размера 10 со значениями от 0 до 1, не включая ни то, ни другое

In [123]:
print(np.linspace(0,1,12)[1:-1])

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


## Отсортировать вектор

In [124]:
x=np.random.random(7)
x.sort()
print(x)

[0.21613025 0.26862545 0.305634   0.71635906 0.77903772 0.83966193
 0.92848951]


##  Проверить, одинаковы ли 2 numpy массива

In [125]:
A=np.random.randint(0,1,2)
B=np.random.randint(0,1,2)
ravno=np.allclose(A,B)
print(ravno)

True


##  Сделать массив неизменяемым

In [126]:
x=np.zeros(5)
x.flags.writeable=False
x[0]=1

ValueError: assignment destination is read-only

## Дан массив 10x2 (точки в декартовой системе координат), преобразовать в полярную

In [127]:
x=np.random.random((10,2))
X,Y=x[:,0],x[:,1]
R=np.hypot(X, Y)
T=np.arctan2(Y,X)
print(R)
print(T)

[0.79102713 0.94347333 0.69489296 1.0416796  0.77938488 0.63234143
 0.85722299 0.91634485 1.03226596 0.36399096]
[1.43705048 1.07786181 0.87802253 0.36599277 1.38907471 0.71681292
 0.53503848 0.65182052 0.67268299 1.35483549]


## Заменить максимальный элемент на ноль

In [128]:
x=np.random.random(10)
x[x.argmax()]=0
print(x)

[0.90597929 0.71907249 0.97432902 0.11277893 0.12775716 0.
 0.88286214 0.81855795 0.91751056 0.80309642]


##  Создать структурированный массив с координатами x, y на сетке в квадрате [0,1]x[0,1]

In [129]:
x=np.zeros((2,2),[('x',float),('y',float)])
x['x'], x['y'] = np.meshgrid(np.linspace(0,1,2),
                             np.linspace(0,1,2))
print(x)

[[(0., 0.) (1., 0.)]
 [(0., 1.) (1., 1.)]]


## Из двух массивов сделать матрицу Коши C (Cij = 1/(xi - yj))

In [130]:
x=np.arange(8)
y=x+0.5
c=1.0/np.subtract.outer(x,y)
print(np.linalg.det(c))

3638.163637117973


##  Найти ближайшее к заданному значению число в заданном массиве

In [131]:
x=np.arange(100)
v=np.random.uniform(0,100)
index=(np.abs(x-v)).argmin()
print(x[index])

98


## Создать структурированный массив, представляющий координату (x,y) и цвет (r,g,b)

In [132]:
x = np.zeros(10, [ ('position', [ ('x', float, 1),
                                   ('y', float, 1)]),
                    ('color',    [ ('r', float, 1),
                                   ('g', float, 1),
                                   ('b', float, 1)])])
print(x)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


C:\Users\kalka\AppData\Local\Temp\ipykernel_6140\2334119483.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  x = np.zeros(10, [ ('position', [ ('x', float, 1),


## Дан массив (100,2) координат, найти расстояние от каждой точки до каждой

In [133]:
import scipy.spatial
Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.69844441 0.71558943 0.17707019 0.73003489 0.54604372
  0.27616073 0.53602889 0.06225504 0.0854131 ]
 [0.69844441 0.         0.23227918 0.52464178 0.20509511 0.48605207
  0.59598189 0.17558347 0.69171175 0.66969847]
 [0.71558943 0.23227918 0.         0.54161814 0.03518386 0.31956306
  0.70228297 0.22526032 0.72909254 0.66165588]
 [0.17707019 0.52464178 0.54161814 0.         0.55459677 0.4121461
  0.26270196 0.35939313 0.18849521 0.14959863]
 [0.73003489 0.20509511 0.03518386 0.55459677 0.         0.35268592
  0.70348589 0.22289733 0.74080189 0.67913771]
 [0.54604372 0.48605207 0.31956306 0.4121461  0.35268592 0.
  0.65763836 0.34916034 0.58409212 0.46868654]
 [0.27616073 0.59598189 0.70228297 0.26270196 0.70348589 0.65763836
  0.         0.48096099 0.2207629  0.33178959]
 [0.53602889 0.17558347 0.22526032 0.35939313 0.22289733 0.34916034
  0.48096099 0.         0.53692372 0.4998766 ]
 [0.06225504 0.69171175 0.72909254 0.18849521 0.74080189 0.58409212
  0.2207629  0.536923

## Преобразовать массив из float в int

In [134]:
Z = np.arange(10, dtype=np.int32)
Z = Z.astype(np.float32, copy=False)

## Каков эквивалент функции enumerate для numpy массивов?

In [135]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


## Сформировать 2D массив с распределением Гаусса

In [136]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.hypot(X, Y)
sigma, mu = 1.0, 0.0
G = np.exp(-((D - mu) ** 2 / (2.0 * sigma ** 2)))
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

##  Отнять среднее из каждой строки в матрице

In [137]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)

## Отсортировать матрицу по n-ому столбцу

In [138]:
Z = np.random.randint(0,10,(3,3))
n = 1  # Нумерация с нуля
print(Z)
print(Z[Z[:,n].argsort()])

[[6 3 3]
 [9 3 7]
 [9 8 1]]
[[6 3 3]
 [9 3 7]
 [9 8 1]]


## Определить, есть ли в 2D массиве нулевые столбцы

In [139]:
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

False


##  Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве (осторожно с повторами)

In [140]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[4. 5. 1. 4. 3. 2. 4. 4. 2. 1.]


## Дан массив (w,h,3) (картинка) dtype=ubyte, посчитать количество различных цветов

In [141]:
w,h = 16,16
I = np.random.randint(0, 2, (h,w,3)).astype(np.ubyte)
F = I[...,0] * 256 * 256 + I[...,1] * 256 + I[...,2]
n = len(np.unique(F))
print(np.unique(I))

[0 1]


## Дан четырехмерный массив, посчитать сумму по последним двум осям

In [142]:
A = np.random.randint(0,10, (3,4,3,4))
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[60 58 46 48]
 [41 45 55 50]
 [49 56 50 67]]


##  Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [143]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


## Поменять 2 строки в матрице

In [144]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


## Рассмотрим набор из 10 троек, описывающих 10 треугольников (с общими вершинами), найти множество уникальных отрезков, составляющих все треугольники

In [145]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 4,  8) ( 4, 28) ( 8, 28) (10, 28) (10, 67) (15, 66) (15, 88) (17, 78)
 (17, 86) (19, 23) (19, 26) (23, 26) (24, 31) (24, 80) (28, 67) (31, 80)
 (49, 54) (49, 60) (54, 60) (65, 70) (65, 83) (66, 88) (70, 77) (70, 83)
 (70, 84) (75, 81) (75, 86) (77, 84) (78, 86) (81, 86)]


## Дан массив C; создать массив A, что np.bincount(A) == C

In [146]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


##  Посчитать среднее, используя плавающее окно

In [147]:
def moving_average(a, n=3):
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n

print(moving_average(np.arange(20), 3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


## Дан вектор Z, построить матрицу, первая строка которой (Z[0],Z[1],Z[2]), каждая последующая сдвинута на 1 (последняя (Z[-3],Z[-2],Z[-1]))

In [148]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


##  Рассмотрим 2 набора точек P0, P1 описания линии (2D) и точку р, как вычислить расстояние от р до каждой линии i (P0[i],P1[i])

In [149]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0] - p[...,0]) * T[:,0] + (P0[:,1] - p[...,1]) * T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U * T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[10.78075183  3.43616925  5.37236589 14.96687952  6.00040225  0.3530545
 11.71024998  5.28540374  4.11710869 14.17122486]


## Дан массив. Написать функцию, выделяющую часть массива фиксированного размера с центром в данном элементе (дополненное значением fill если необходимо)

In [150]:
Z = np.random.randint(0,10, (10,10))
shape = (5,5)
fill  = 0
position = (1,1)
R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)
R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P - Rs//2)
Z_stop  = (P + Rs//2)+Rs%2
R_start = (R_start - np.minimum(Z_start, 0)).tolist()
Z_start = (np.maximum(Z_start, 0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()
r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[1 9 4 6 0 6 8 4 0 5]
 [0 2 7 0 6 7 2 5 2 5]
 [9 1 9 9 5 2 6 2 7 3]
 [2 5 4 4 0 1 1 0 4 6]
 [7 7 0 6 4 4 0 6 9 0]
 [8 8 0 2 7 7 0 0 9 0]
 [2 7 1 9 3 3 9 8 4 0]
 [2 1 3 4 0 1 1 8 9 3]
 [6 4 5 2 5 5 4 3 5 1]
 [1 9 1 5 5 3 2 4 3 4]]
[[0 0 0 0 0]
 [0 1 9 4 6]
 [0 0 2 7 0]
 [0 9 1 9 9]
 [0 2 5 4 4]]


C:\Users\kalka\AppData\Local\Temp\ipykernel_6140\909365175.py:19: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  R[r] = Z[z]


##  Посчитать ранг матрицы

In [151]:
Z = np.random.uniform(0,1,(10,10))
rank = np.linalg.matrix_rank(Z)

## Z = np.random.uniform(0,1,(10,10)) rank = np.linalg.matrix_rank(Z)

In [152]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

3


## Извлечь все смежные 3x3 блоки из 10x10 матрицы

In [153]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0] - n)
j = 1 + (Z.shape[1] - n)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[0 2 2]
   [2 0 3]
   [3 3 2]]

  [[2 2 1]
   [0 3 2]
   [3 2 0]]

  [[2 1 1]
   [3 2 3]
   [2 0 1]]

  [[1 1 4]
   [2 3 2]
   [0 1 2]]

  [[1 4 2]
   [3 2 1]
   [1 2 4]]

  [[4 2 4]
   [2 1 3]
   [2 4 0]]

  [[2 4 0]
   [1 3 2]
   [4 0 3]]

  [[4 0 1]
   [3 2 4]
   [0 3 0]]]


 [[[2 0 3]
   [3 3 2]
   [0 1 3]]

  [[0 3 2]
   [3 2 0]
   [1 3 0]]

  [[3 2 3]
   [2 0 1]
   [3 0 4]]

  [[2 3 2]
   [0 1 2]
   [0 4 2]]

  [[3 2 1]
   [1 2 4]
   [4 2 3]]

  [[2 1 3]
   [2 4 0]
   [2 3 3]]

  [[1 3 2]
   [4 0 3]
   [3 3 3]]

  [[3 2 4]
   [0 3 0]
   [3 3 3]]]


 [[[3 3 2]
   [0 1 3]
   [1 0 1]]

  [[3 2 0]
   [1 3 0]
   [0 1 1]]

  [[2 0 1]
   [3 0 4]
   [1 1 4]]

  [[0 1 2]
   [0 4 2]
   [1 4 1]]

  [[1 2 4]
   [4 2 3]
   [4 1 1]]

  [[2 4 0]
   [2 3 3]
   [1 1 4]]

  [[4 0 3]
   [3 3 3]
   [1 4 4]]

  [[0 3 0]
   [3 3 3]
   [4 4 4]]]


 [[[0 1 3]
   [1 0 1]
   [4 4 0]]

  [[1 3 0]
   [0 1 1]
   [4 0 2]]

  [[3 0 4]
   [1 1 4]
   [0 2 2]]

  [[0 4 2]
   [1 4 1]
   [2 2 1]]

  [[4 2 3]
   

## Рассмотрим множество матриц (n,n) и множество из p векторов (n,1). Посчитать сумму p произведений матриц (результат имеет размерность (n,1))

In [154]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


## Дан массив 16x16, посчитать сумму по блокам 4x4

In [155]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)

##  Написать игру "жизнь"

In [156]:
print('игру "жизнь"')

игру "жизнь"


In [157]:
def iterate(Z):
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])
    birth = (N == 3) & (Z[1:-1,1:-1]==0)
    survive = ((N == 2) | (N == 3)) & (Z[1:-1,1:-1] == 1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z
Z = np.random.randint(0,2,(5,5))
for i in range(100):
    print(Z)
    Z = iterate(Z)

[[1 0 0 1 0]
 [1 1 0 1 1]
 [1 0 1 0 0]
 [1 0 0 1 0]
 [0 1 0 1 1]]
[[0 0 0 0 0]
 [0 0 0 1 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 0]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 1 1 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[0 0 0 0 

## Найти n наибольших значений в массиве

In [158]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

print (Z[np.argpartition(-Z,n)[:n]])

[9998 9999 9996 9997 9995]


##  Построить прямое произведение массивов (все комбинации с каждым элементом)

In [159]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = map(len, arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print(cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


## Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [160]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = (C.sum(axis=(1,2,3)) >= B.shape[1]).nonzero()[0]
print(rows)

[0 1 2 3 6]


##  Дана 10x3 матрица, найти строки из неравных значений (например [2,2,3])

In [161]:
Z = np.random.randint(0,5,(10,3))
E = np.logical_and.reduce(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(Z)
print(U)

[[0 2 4]
 [2 1 4]
 [1 4 4]
 [2 1 3]
 [4 4 2]
 [4 3 2]
 [4 3 3]
 [2 3 3]
 [2 0 0]
 [2 3 4]]
[[0 2 4]
 [2 1 4]
 [1 4 4]
 [2 1 3]
 [4 4 2]
 [4 3 2]
 [4 3 3]
 [2 3 3]
 [2 0 0]
 [2 3 4]]


## Преобразовать вектор чисел в матрицу бинарных представлений

In [162]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


## Дан двумерный массив. Найти все различные строки

In [163]:
Z = np.random.randint(0, 2, (6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 0]
 [0 0 1]
 [0 1 0]
 [1 1 0]
 [1 1 1]]
